name: macOS-python

on: [push]

jobs:
  build-test:

    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install-build-dependencies
      run: brew install eigen
    - name: submodule
      run: git submodule update --init --recursive
    - name: pip-install-pySequentialLineSearch
      run: pip install ./
    - name: install-test-dependencies
      run: |
        pip install joblib matplotlib seaborn scipy
        brew tap homebrew/cask-fonts && brew cask install font-linux-biolinum
        brew cask install mactex-no-gui
    - name: test
      run: |
        export PATH=$PATH:/Library/TeX/texbin
        python ./python-examples/acquisition-func-comparison.py
        python ./python-examples/simple.py
        python ./python-examples/custom-initial-slider.py
        python ./python-examples/map-vs-fixed-hyperparams.py
        python ./python-examples/kernel-comparison.py
